# Generated by Django 3.0.6 on 2020-06-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='college_id',
            new_name='college',
        ),
    ]
